apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gs-safety
  namespace: gs-safety
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: gs.emul.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gs-safety
                port:
                  number: 3000
