import { GuidanceSchema } from "@/contracts";
import type { KnowledgeChunk } from "./types";

export function sampleGuidance() {
  return GuidanceSchema.parse({
    incidentId: "INC-TEST",
    eventId: "EVENT-TEST",
    runId: "RUN-TEST",
    workerId: "WORKER-A",
    guidanceId: "GUIDANCE-TEST",
    guidanceVersion: 1,
    updateKind: "primary",
    primaryGuidanceVersion: 1,
    simulationMode: "equipment",
    hazardIds: ["HAZARD-TEST"],
    hazardType: "equipment",
    priority: "high",
    actionCode: "ALERT_HAZARD",
    routeVersion: null,
    stepId: null,
    mapId: "MAP-TEST",
    mapVersion: "1.0.0",
    floorId: "GROUND",
    waypoints: [],
    destinationId: null,
    profileVersion: 1,
    profileSnapshot: {
      workerId: "WORKER-A",
      version: 1,
      preferredLocale: "en",
      locale: "en",
      canUseStairs: false,
      speedMps: null,
      needsAssistance: true,
      needsCompanion: false,
      notificationPreferences: { voice: true, vibration: true },
      confirmedAt: "2026-09-21T10:00:00Z",
    },
    locale: "en",
    requestedLocale: "en",
    fallbackLocaleUsed: false,
    templateCatalogVersion: "1.0.0",
    messageKey: "ALERT_HAZARD",
    primaryMessageKey: "ALERT_HAZARD",
    messageArgs: {},
    primaryMessage: "Equipment alert",
    managerExplanationKo: "장비 경보",
    supplementalExplanation: null,
    evidence: [],
    mode: "template",
    generatedAt: "2026-09-21T10:00:00Z",
    expiresAt: "2026-09-21T10:01:00Z",
  });
}

export const sampleChunk: KnowledgeChunk = {
  documentId: "EQ-001",
  documentVersion: "0.1.0",
  chunkId: "EQ-001:0.1.0:procedure",
  content:
    "The engine detected overlap with equipment movement. 엔진이 장비 이동 영역의 겹침을 감지했습니다.",
  contentHash: "test-content-hash",
  metadata: {
    documentId: "EQ-001",
    title: "Equipment approach",
    siteIds: ["SITE-CONSTRUCTION-01"],
    simulationType: "equipment",
    simulationTypes: ["equipment"],
    hazardTypes: ["equipment"],
    applicableRoles: ["worker"],
    applicableZoneIds: [],
    substanceIds: [],
    profileConditions: {},
    actionCodes: ["ALERT_HAZARD"],
    language: "ko",
    version: "0.1.0",
    synthetic: true,
    approvalStatus: "approved_for_demo",
    effectiveFrom: "2026-01-01",
    expiresAt: "2030-01-01",
    reviewedBy: "test-reviewer",
    reviewedAt: "2026-09-21T08:00:00Z",
    reviewedContentHash: "test-reviewed-hash",
    sourceReference: "synthetic://safety-simulator/EQ-001",
    requiredScenarioPolicy: null,
    decisionKey: null,
    reviewedSupplementalExplanation: {
      ko: "엔진이 장비 이동 영역의 겹침을 감지했습니다.",
      en: "The engine detected overlap with equipment movement.",
    },
  },
};

export const sampleSupplement = {
  actionCode: "ALERT_HAZARD",
  locale: "en",
  supplementalExplanation: "The engine detected overlap with equipment movement.",
  evidence: [{ documentId: "EQ-001", documentVersion: "0.1.0", chunkId: "EQ-001:0.1.0:procedure" }],
} as const;
