import type { Locale, ResponseState } from "@/contracts";

const ko = {
  title: "작업자 브라우저 미리보기",
  currentAction: "지금 해야 할 행동",
  map: "내 위치와 현재 경로",
  noGuide: "현재 유효한 안내가 없습니다",
  waitGuide:
    "관제의 현재 실행과 새 안내를 기다리고 있습니다. 안내가 만료되거나 변경되면 이전 경로는 표시하지 않습니다.",
  understood: "안내를 이해했습니다",
  help: "도움이 필요합니다",
  arrived: "목적지에 도착했습니다",
  replay: "안내 다시 듣기",
  voiceOn: "음성 켜짐",
  voiceOff: "음성 켜기",
  responses: "내 응답 상태",
  receipt: "기기 수신",
  displayed: "화면 표시",
  spoken: "음성 완료",
  understanding: "이해 확인",
  assistance: "도움 요청",
  arrival: "도착 확인",
  pending: "아직 기록 없음",
  generated: "안내 생성",
  expires: "유효 기한",
  source: "위치 출처",
  inputSource: "입력 구분",
  live: "실측 입력 / live",
  synthetic: "합성 입력 / synthetic",
  unknown: "입력 출처 미확인 / unknown",
  observed: "위치 관측",
  received: "상태 수신",
  positionUnknown: "위치 미확인",
  positionStale: "마지막 위치 · 오래됨",
  positionKnown: "현재 위치",
  mock: "모의 위치",
  video: "영상 표식",
  uwb: "UWB 측정",
  manual: "수동 입력",
  connected: "실시간 연결",
  reconnecting: "연결 확인 중 · 마지막 수신 시각을 확인하세요",
  noRoute: "현재 안내에는 이동 경로가 없습니다.",
  explanation: "추가 설명과 출처",
  route: "경로 버전",
  destination: "목적지",
  noDestination: "이동 목적지 없음",
  support: "관제 지원 상태",
  none: "요청 전",
  requested: "요청 전달",
  assigned: "담당자 배정",
  accepted: "담당자 수락",
  completed: "지원 완료",
  previewScope: "브라우저 미리보기 · Android 실제 기기 검증과 별개입니다.",
  invalidMap: "현재 실행과 지도 버전이 일치하지 않아 위치·경로를 표시하지 않습니다.",
  scope: "시뮬레이션 / SIMULATION · 서산 HVO 현장 참고 / 상세 배치 재구성",
  switchAccount: "작업자 변경",
  equipment: "중장비 접근",
  fireGas: "화재·가스",
  routeLegend: "선: 검증 경로 · 빗금: 위험 영역 · 점: 내 위치 · +X/+Y: 현장 로컬 축",
  audioState: "브라우저 음성 상태",
  explicitArrival: "도착 버튼은 현재 위치에 대한 서버 검증을 요청합니다.",
};

const en: typeof ko = {
  title: "Worker browser preview",
  currentAction: "Your current action",
  map: "My position and current route",
  noGuide: "No current valid guidance",
  waitGuide: "Waiting for the current run and new guidance. Expired or replaced routes are hidden.",
  understood: "I understand the guidance",
  help: "I need assistance",
  arrived: "I have reached the destination",
  replay: "Listen again",
  voiceOn: "Voice enabled",
  voiceOff: "Enable voice",
  responses: "My response status",
  receipt: "Device received",
  displayed: "Screen displayed",
  spoken: "Voice completed",
  understanding: "Understanding confirmed",
  assistance: "Help requested",
  arrival: "Arrival confirmed",
  pending: "Not yet recorded",
  generated: "Generated",
  expires: "Expires",
  source: "Position source",
  inputSource: "Input provenance",
  live: "Live measurement / live",
  synthetic: "Synthetic input / synthetic",
  unknown: "Input provenance unknown / unknown",
  observed: "Position observed",
  received: "State received",
  positionUnknown: "Position unknown",
  positionStale: "Last position · stale",
  positionKnown: "Current position",
  mock: "Simulated position",
  video: "Video marker",
  uwb: "UWB measurement",
  manual: "Manual entry",
  connected: "Connected live",
  reconnecting: "Checking connection · review the last received time",
  noRoute: "This guidance has no movement route.",
  explanation: "Additional explanation and sources",
  route: "Route version",
  destination: "Destination",
  noDestination: "No movement destination",
  support: "Operations support status",
  none: "No request",
  requested: "Request delivered",
  assigned: "Assignee appointed",
  accepted: "Assignee accepted",
  completed: "Support completed",
  previewScope: "Browser preview · separate from Android physical device verification.",
  invalidMap: "The run and map versions differ. Position and route are hidden.",
  scope: "SIMULATION · Seosan HVO context / reconstructed detailed layout",
  switchAccount: "Change worker",
  equipment: "Equipment proximity",
  fireGas: "Fire and gas",
  routeLegend: "Line: validated route · hatch: hazard · dot: my position · +X/+Y: local site axes",
  audioState: "Browser voice status",
  explicitArrival: "The arrival button requests server verification of your current position.",
};

export function workerCopy(locale: Locale) {
  return locale === "en" ? en : ko;
}

export function workerTime(value: string | null, locale: Locale): string {
  return value
    ? new Date(value).toLocaleTimeString(locale === "en" ? "en-GB" : "ko-KR", { hour12: false })
    : workerCopy(locale).pending;
}

export function voiceLabel(value: ResponseState["voiceStatus"] | "idle", locale: Locale): string {
  const labels = {
    ko: {
      pending: "재생 전",
      idle: "재생 대기",
      playing: "재생 중",
      "stop-requested": "중지 요청 · 기기 확인 없음",
      completed: "재생 완료",
      failed: "재생 실패",
      unsupported: "브라우저 미지원",
      cancelled: "재생 취소",
    },
    en: {
      pending: "Not played",
      idle: "Ready",
      playing: "Playing",
      "stop-requested": "Stop requested · device unconfirmed",
      completed: "Completed",
      failed: "Failed",
      unsupported: "Unsupported by browser",
      cancelled: "Cancelled",
    },
  };
  return labels[locale][value];
}
