import type { Guidance, SimulationMode, SimulationSnapshot } from "@gs-safety/contracts";

export function runFixture(mode: SimulationMode = "equipment"): SimulationSnapshot {
  return {
    contractVersion: "1.0.0",
    streamId: "test-stream",
    sequence: 0,
    mode,
    run: {
      positionInput: "scenario",
      runId: `run-${mode}`,
      scenarioId: "fixture",
      status: "idle",
      virtualTimeMs: 0,
      speed: 1,
      seed: 20260921,
      version: 0,
      mapId: "MAP-01",
      mapVersion: "1.0",
      startedAt: null,
      updatedAt: "2026-09-21T09:00:00Z",
    },
    workers: [],
    equipment: {
      id: "EQUIPMENT-A",
      presetId: "fixture",
      position: { x: 0, y: 0 },
      headingDeg: 0,
      speedMps: 0,
      slewDeg: 0,
      boomAngleDeg: 0,
      boomLengthM: null,
      trolleyM: null,
      hookHeightM: null,
      geometryVersion: 1,
      positionSource: "mock",
      positionInputSource: "synthetic",
      tableLinked: false,
      positionStatus: "known",
      lastObservedAt: "2026-09-21T09:00:00Z",
    },
    hazards: [],
    closedEdgeIds: [],
    incidents: [],
    events: [],
    cctv: [],
  };
}

export function guidanceFixture(): Guidance {
  return {
    incidentId: "incident-1",
    eventId: "event-1",
    runId: "run-equipment",
    workerId: "WORKER-A",
    guidanceId: "guidance-1",
    guidanceVersion: 1,
    updateKind: "primary",
    primaryGuidanceVersion: 1,
    simulationMode: "equipment",
    hazardIds: ["hazard-1"],
    hazardType: "equipment",
    priority: "high",
    actionCode: "REQUEST_ASSISTANCE",
    routeVersion: null,
    stepId: null,
    mapId: "MAP-01",
    mapVersion: "1.0",
    floorId: "F1",
    waypoints: [],
    destinationId: null,
    profileVersion: 1,
    profileSnapshot: {
      workerId: "WORKER-A",
      version: 1,
      preferredLocale: "ko",
      locale: "ko",
      canUseStairs: false,
      speedMps: { min: 0.3, max: 0.7 },
      needsAssistance: true,
      needsCompanion: true,
      notificationPreferences: { voice: true, vibration: true },
      confirmedAt: "2026-09-21T08:00:00Z",
    },
    locale: "ko",
    requestedLocale: "ko",
    fallbackLocaleUsed: false,
    templateCatalogVersion: "1.0.0",
    messageKey: "request-assistance",
    primaryMessageKey: "request-assistance",
    messageArgs: {},
    primaryMessage: "지원을 요청하세요.",
    managerExplanationKo: "지원 요청",
    supplementalExplanation: null,
    evidence: [],
    mode: "template",
    generatedAt: "2026-09-21T09:00:00Z",
    expiresAt: "2026-09-21T09:10:00Z",
  };
}

export function snapshotWithGuidance(guidance = guidanceFixture()): SimulationSnapshot {
  const snapshot = runFixture();
  return {
    ...snapshot,
    incidents: [
      {
        incidentId: guidance.incidentId,
        runId: snapshot.run.runId,
        version: 1,
        hazardIds: guidance.hazardIds,
        hazardType: guidance.hazardType,
        priority: guidance.priority,
        status: "active",
        acknowledgedAt: null,
        assignedTo: null,
        supportStatus: "none",
        hazardClearedAt: null,
        passageReopenedAt: null,
        closedAt: null,
        firstGuidance: [guidance],
        currentGuidance: [guidance],
        audit: [],
      },
    ],
  };
}
