import type {
  Guidance,
  Incident,
  IncidentAction,
  Session,
  SimulationSnapshot,
  WorkerResponse,
} from "@/contracts";

export const now = "2026-09-21T09:00:10.000Z";
export const sentAt = "2026-09-21T09:00:00.000Z";
export const profile = {
  workerId: "WORKER-A",
  version: 1,
  preferredLocale: "en",
  locale: "en",
  canUseStairs: false,
  speedMps: { min: 0.3, max: 0.7 },
  needsAssistance: true,
  needsCompanion: true,
  notificationPreferences: { voice: true, vibration: true },
  confirmedAt: sentAt,
} as const;
export const guidance: Guidance = {
  incidentId: "INCIDENT-A",
  eventId: "GUIDANCE-EVENT-A",
  runId: "RUN-A",
  workerId: "WORKER-A",
  guidanceId: "GUIDANCE-A",
  guidanceVersion: 1,
  updateKind: "primary",
  primaryGuidanceVersion: 1,
  simulationMode: "equipment",
  hazardIds: ["HAZARD-A"],
  hazardType: "equipment",
  priority: "high",
  actionCode: "FOLLOW_VALIDATED_ROUTE",
  routeVersion: 1,
  stepId: "STEP-A",
  mapId: "MAP-A",
  mapVersion: "1",
  floorId: "GROUND",
  destinationId: "REFUGE-A",
  waypoints: [
    { x: 0, y: 0, nodeId: "START", floorId: "GROUND" },
    { x: 10, y: 10, nodeId: "REFUGE-A", floorId: "GROUND" },
  ],
  profileVersion: 1,
  profileSnapshot: profile,
  locale: "en",
  requestedLocale: "en",
  fallbackLocaleUsed: false,
  templateCatalogVersion: "1",
  messageKey: "guidance.follow_validated_route",
  primaryMessageKey: "guidance.follow_validated_route",
  messageArgs: { destinationId: "REFUGE-A" },
  primaryMessage: "Move to REFUGE-A.",
  managerExplanationKo: "지정 지점으로 이동",
  supplementalExplanation: null,
  evidence: [],
  mode: "template",
  generatedAt: sentAt,
  expiresAt: "2026-09-21T09:01:00.000Z",
};
export const incident: Incident = {
  incidentId: "INCIDENT-A",
  runId: "RUN-A",
  version: 1,
  hazardIds: ["HAZARD-A"],
  hazardType: "equipment",
  priority: "high",
  status: "active",
  acknowledgedAt: null,
  assignedTo: null,
  supportStatus: "none",
  hazardClearedAt: null,
  passageReopenedAt: null,
  closedAt: null,
  firstGuidance: [guidance],
  currentGuidance: [guidance],
  audit: [],
};
export const snapshot: SimulationSnapshot = {
  contractVersion: "1.0.0",
  streamId: "incident-test-stream",
  sequence: 0,
  mode: "equipment",
  run: {
    positionInput: "scenario",
    runId: "RUN-A",
    scenarioId: "SCENARIO-A",
    status: "running",
    virtualTimeMs: 10000,
    speed: 1,
    seed: 1,
    version: 7,
    mapId: "MAP-A",
    mapVersion: "1",
    startedAt: sentAt,
    updatedAt: now,
  },
  workers: [
    {
      workerId: "WORKER-A",
      profile,
      position: { x: 10, y: 10 },
      positionSource: "mock",
      positionInputSource: "synthetic",
      positionStatus: "known",
      lastObservedAt: now,
      currentGuidance: guidance,
      virtual: true,
      response: {
        receivedAt: null,
        displayedAt: null,
        spokenAt: null,
        understoodAt: null,
        helpRequestedAt: null,
        arrivedAt: null,
        voiceStatus: "pending",
      },
    },
  ],
  equipment: {
    id: "EQUIPMENT-A",
    presetId: "PRESET-A",
    position: { x: 0, y: 0 },
    headingDeg: 0,
    speedMps: 0,
    slewDeg: 0,
    boomAngleDeg: 0,
    boomLengthM: null,
    trolleyM: null,
    hookHeightM: null,
    geometryVersion: 1,
    positionSource: "mock",
    positionInputSource: "synthetic",
    tableLinked: false,
    positionStatus: "known",
    lastObservedAt: now,
  },
  hazards: [
    {
      hazardId: "HAZARD-A",
      hazardType: "equipment",
      priority: "high",
      polygon: [],
      active: true,
      floorId: "GROUND",
      source: "engine",
      observedAt: now,
      sensorStatus: "not-applicable",
      affectedWorkerIds: ["WORKER-A"],
      reason: "approach",
      zoneId: null,
      substanceId: null,
    },
  ],
  closedEdgeIds: ["EDGE-A"],
  incidents: [incident],
  events: [],
  cctv: [],
};
export function session(role: Session["role"] = "admin"): Session {
  return {
    sessionId: `SESSION-${role}`,
    role,
    actorId: `${role}-a`,
    token: "test-token",
    workerId: role === "worker" ? "WORKER-A" : null,
    deviceRole: null,
    expiresAt: "2026-09-21T10:00:00.000Z",
  };
}
export function action(name: IncidentAction["action"] = "acknowledge"): IncidentAction {
  return {
    mode: "equipment",
    expectedVersion: 7,
    requestId: `request-${name}`,
    incidentId: "INCIDENT-A",
    expectedIncidentVersion: 1,
    action: name,
  };
}
export function response(name: WorkerResponse["response"] = "received"): WorkerResponse {
  return {
    mode: "equipment",
    runId: "RUN-A",
    workerId: "WORKER-A",
    requestId: `response-${name}`,
    incidentId: "INCIDENT-A",
    guidanceId: "GUIDANCE-A",
    guidanceVersion: 1,
    response: name,
    occurredAt: now,
  };
}
export const managerContext = { session: session(), now };
export const workerContext = {
  session: session("worker"),
  now,
  arrivalTargets: {},
  arrivalToleranceM: 2,
};
