export const CLOCK_BINDING_INPUT =
  "docs/goal-runs/GS-SAFETY-SIM-001-20260921T084101Z/qa/clock-binding-v1.1.md";
export const OPERATIONAL_SOURCE_INPUTS = [
  "docs/goal-runs/GS-SAFETY-SIM-001-20260921T084101Z/evidence/research/manufacturer/manifest.json",
  "resources/blender/safety-simulator/mobile-cranes/tadano-gr250n4-rig.json",
  "resources/blender/safety-simulator/mobile-cranes/liebherr-ltm1050-rig.json",
  "resources/blender/safety-simulator/maeda-site/maeda/rig-catalog.json",
  "resources/blender/safety-simulator/lattice-cranes/liebherr-lr1100-rig.json",
  "resources/blender/safety-simulator/lattice-cranes/lr-pivot-correction-01/verify-pivot.mjs",
] as const;
export const CALIBRATION_REPORT_PATH =
  /^tools\/calibration\/(?:http-(?:bridge-)?smoke-results[^/]*|benchmark-results)\.json$/;
export const EXECUTION_REPORT_PATHS: ReadonlySet<string> = new Set([
  "tools/calibration/http-bridge-recovery-red-20260921T110814494Z.json",
  "data/scenarios/self-check-results.json",
  "data/scenarios/self-check.md",
  "apps/mobile/test/presentation/capture-manifest.json",
  "apps/mobile/test/presentation/candidate2-before/priority-first-screen-ko-375-200.png",
  "apps/mobile/test/presentation/candidate2-before/visual-evidence.tar.gz",
  "apps/mobile/test/presentation/candidate3-ui-evidence.md",
  "apps/mobile/test/presentation/candidate4-ui-evidence.md",
  "apps/mobile/test/presentation/priority-review-a.md",
  "apps/mobile/test/presentation/priority-review-b.md",
  "apps/mobile/test/setup/capture-manifest.json",
  "apps/mobile/test/setup/final-ui-evidence.md",
  "tests/negative-fixtures/wall-clock-v1.1/producer-run.json",
  "tests/negative-fixtures/wall-clock-v1.1/producer-run.final.json",
  "tests/negative-fixtures/wall-clock-v1.1/mock-sqlite-results.json",
  "tests/negative-fixtures/wall-clock-v1.1/mock-sqlite-final-results.json",
]);

export const SOURCE_INPUTS = [
  CLOCK_BINDING_INPUT,
  ...OPERATIONAL_SOURCE_INPUTS,
  "app",
  "src",
  "packages",
  "scripts",
  "tests",
  "tools",
  "public",
  "drizzle",
  "knowledge",
  "apps/mobile",
  "data/equipment",
  "data/maps",
  "data/policies",
  "data/scenarios",
  "data/knowledge/drafts",
  "data/knowledge/revisions",
  ...KNOWLEDGE_REVIEW_INPUTS,
  "data/knowledge/runtime/README.md",
  "data/knowledge/runtime/prepare-embedding.sh",
  "data/knowledge/runtime/prepare-llm.sh",
  "data/knowledge/runtime/start-llm.sh",
  "data/knowledge/runtime/probe-embedding.mjs",
  "data/knowledge/runtime/embedding-sha256.txt",
  "resources/blender/safety-simulator",
  "resources/blender/spierings-sk1265-at6",
  "docs/contracts",
  "docs/demo-runbook.md",
  "docs/design",
  "resources/design",
  "DESIGN.md",
  "README.md",
  "consistency-report.md",
  "package.json",
  "package-lock.json",
  "pnpm-lock.yaml",
  "pnpm-workspace.yaml",
  "tsconfig.json",
  "biome.json",
  "next.config.ts",
  "postcss.config.mjs",
  "vitest.config.ts",
  "drizzle.config.ts",
  ".env.example",
  ".gitignore",
  ".nvmrc",
  ".node-version",
  "Dockerfile",
  "compose.yaml",
  "docker-compose.yml",
  ".dockerignore",
] as const;
const EQUIPMENT = [
  ["sk1265-derived", "sk1265-at6"],
  ["mobile-cranes", "tadano-gr250n4"],
  ["mobile-cranes", "liebherr-ltm1050"],
  ["maeda-site/maeda", "maeda-mc305"],
  ["lattice-cranes", "liebherr-lr1100"],
  ["lattice-cranes", "liebherr-172ecb"],
] as const;
export const REQUIRED_INPUTS = [
  CLOCK_BINDING_INPUT,
  ...OPERATIONAL_SOURCE_INPUTS,
  "package.json",
  "package-lock.json",
  "tsconfig.json",
  ".env.example",
  "app/layout.tsx",
  "src/server/db/seed.ts",
  "drizzle/0000_persistence.sql",
  "packages/contracts/src/index.ts",
  "data/equipment/catalog.json",
  "data/equipment/catalog.draft.json",
  "data/maps/site-construction-01.json",
  "data/policies",
  "data/scenarios/equipment",
  "data/scenarios/fire-gas",
  "consistency-report.md",
  ...KNOWLEDGE_DRAFT_INPUTS,
  ...KNOWLEDGE_REVISION_INPUTS,
  ...KNOWLEDGE_REVIEW_INPUTS,
  "tests/rag-test-cases.json",
  "tests/negative-fixtures",
  "DESIGN.md",
  "docs/contracts/v1.md",
  "docs/demo-runbook.md",
  "apps/mobile/pubspec.yaml",
  "apps/mobile/pubspec.lock",
  "apps/mobile/lib/main.dart",
  "apps/mobile/android/app/src/main/AndroidManifest.xml",
  "public/assets/site/hvo-demo.glb",
  "resources/blender/safety-simulator/artifact-manifest.json",
  "resources/blender/safety-simulator/maeda-site/site/hvo-demo.blend",
  "resources/blender/spierings-sk1265-at6/spierings_sk1265_at6.blend",
  ...EQUIPMENT.flatMap(([folder, id]) => [
    `public/assets/cranes/${id}.glb`,
    `resources/blender/safety-simulator/${folder}/${id}.blend`,
  ]),
  ...(
    [
      ["common", "COMMON", 4],
      ["equipment", "EQ", 6],
      ["fire-gas", "FG", 8],
    ] as const
  ).flatMap(([folder, prefix, count]) =>
    Array.from(
      { length: count },
      (_, index) => `knowledge/${folder}/${prefix}-${String(index + 1).padStart(3, "0")}.md`,
    ),
  ),
] as const;
const APK_PATHS = [
  "apps/mobile/build/app/outputs/flutter-apk/app-debug.apk",
  "apps/mobile/build/app/outputs/flutter-apk/app-profile.apk",
  "apps/mobile/build/app/outputs/flutter-apk/app-release.apk",
] as const;
export const ARTIFACT_INPUTS = [
  ...PROVENANCE_ARTIFACT_INPUTS,
  "next-env.d.ts",
  ".next/types",
  ...APK_PATHS,
  "apps/mobile/build/app/outputs/bundle/release/app-release.aab",
  ".next/BUILD_ID",
  ".next/package.json",
  ".next/server",
  ".next/static",
  ".next/build-manifest.json",
  ".next/app-build-manifest.json",
  ".next/app-path-routes-manifest.json",
  ".next/prerender-manifest.json",
  ".next/routes-manifest.json",
  ".next/required-server-files.json",
  ".next/images-manifest.json",
  ".next/react-loadable-manifest.json",
  ".next/dynamic-css-manifest.json",
] as const;
export const REQUIRED_ARTIFACTS = [
  ...PROVENANCE_ARTIFACT_INPUTS.map((path) => ({ requirement: path, expectedPaths: [path] })),
  { requirement: "android-apk", expectedPaths: APK_PATHS },
  { requirement: "web-build-id", expectedPaths: [".next/BUILD_ID"] },
  { requirement: "web-package", expectedPaths: [".next/package.json"] },
  { requirement: "web-server", expectedPaths: [".next/server/app"] },
  { requirement: "web-static", expectedPaths: [".next/static"] },
] as const;
export const EXCLUDED_DIRECTORIES = new Set([
  "node_modules",
  ".git",
  ".omo",
  ".cache",
  ".gradle",
  ".dart_tool",
  "__pycache__",
  "coverage",
  "logs",
  "evidence",
  "qa",
  "screenshots",
  "test-results",
  "playwright-report",
  "blob-report",
  "tmp",
  "temp",
]);
export const SOURCE_BUILD_DIRECTORIES = new Set([
  "build",
  "dist",
  "out",
  ".next",
  ".output",
  ".turbo",
  "artifacts",
]);

import {
  KNOWLEDGE_DRAFT_INPUTS,
  KNOWLEDGE_REVIEW_INPUTS,
  KNOWLEDGE_REVISION_INPUTS,
  PROVENANCE_ARTIFACT_INPUTS,
} from "./candidate-manifest-knowledge";
