import { SimulationSnapshotSchema } from "@/contracts";

export const clientSnapshotFixture = SimulationSnapshotSchema.parse({
  contractVersion: "1.0.0",
  streamId: "00000000-0000-4000-8000-000000000001",
  sequence: 10,
  mode: "equipment",
  run: {
    runId: "run1",
    scenarioId: "test",
    status: "idle",
    virtualTimeMs: 0,
    speed: 1,
    seed: 1,
    version: 4,
    mapId: "map",
    mapVersion: "1",
    startedAt: null,
    updatedAt: "2026-09-21T09:00:00Z",
  },
  workers: [],
  equipment: {
    id: "EQUIPMENT-A",
    presetId: "sk1265-at6",
    position: { x: 30, y: 25 },
    headingDeg: 0,
    speedMps: 0,
    slewDeg: 0,
    boomAngleDeg: 0,
    boomLengthM: null,
    trolleyM: null,
    hookHeightM: null,
    geometryVersion: 1,
    positionSource: "mock",
    tableLinked: false,
    positionStatus: "known",
    lastObservedAt: null,
  },
  hazards: [],
  closedEdgeIds: [],
  incidents: [],
  events: [],
  cctv: [],
});
